{
  "cells": [
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "2fb7gj1na_-x",
        "outputId": "c1811465-e836-4d79-de21-cb0f2506ba9e"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Requirement already satisfied: tweepy in /home/nihar/.local/lib/python3.8/site-packages (4.10.0)\n",
            "Requirement already satisfied: oauthlib<4,>=3.2.0 in /home/nihar/.local/lib/python3.8/site-packages (from tweepy) (3.2.0)\n",
            "Requirement already satisfied: requests-oauthlib<2,>=1.2.0 in /home/nihar/.local/lib/python3.8/site-packages (from tweepy) (1.3.1)\n",
            "Requirement already satisfied: requests<3,>=2.27.0 in /home/nihar/.local/lib/python3.8/site-packages (from tweepy) (2.28.1)\n",
            "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests<3,>=2.27.0->tweepy) (1.25.8)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests<3,>=2.27.0->tweepy) (2.8)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests<3,>=2.27.0->tweepy) (2019.11.28)\n",
            "Requirement already satisfied: charset-normalizer<3,>=2 in /home/nihar/.local/lib/python3.8/site-packages (from requests<3,>=2.27.0->tweepy) (2.1.0)\n",
            "Note: you may need to restart the kernel to use updated packages.\n"
          ]
        }
      ],
      "source": [
        "%pip install tweepy"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "QkGnKKpcbG7z",
        "outputId": "e8d36a29-4546-4862-af7a-0ad1c13d9d27"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Requirement already satisfied: transformers in /home/nihar/.local/lib/python3.8/site-packages (4.21.1)\n",
            "Requirement already satisfied: pyyaml>=5.1 in /usr/lib/python3/dist-packages (from transformers) (5.3.1)\n",
            "Requirement already satisfied: packaging>=20.0 in /home/nihar/.local/lib/python3.8/site-packages (from transformers) (21.3)\n",
            "Requirement already satisfied: requests in /home/nihar/.local/lib/python3.8/site-packages (from transformers) (2.28.1)\n",
            "Requirement already satisfied: tokenizers!=0.11.3,<0.13,>=0.11.1 in /home/nihar/.local/lib/python3.8/site-packages (from transformers) (0.12.1)\n",
            "Requirement already satisfied: numpy>=1.17 in /home/nihar/.local/lib/python3.8/site-packages (from transformers) (1.23.2)\n",
            "Requirement already satisfied: regex!=2019.12.17 in /home/nihar/.local/lib/python3.8/site-packages (from transformers) (2022.8.17)\n",
            "Requirement already satisfied: tqdm>=4.27 in /home/nihar/.local/lib/python3.8/site-packages (from transformers) (4.64.0)\n",
            "Requirement already satisfied: huggingface-hub<1.0,>=0.1.0 in /home/nihar/.local/lib/python3.8/site-packages (from transformers) (0.8.1)\n",
            "Requirement already satisfied: filelock in /home/nihar/.local/lib/python3.8/site-packages (from transformers) (3.8.0)\n",
            "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/nihar/.local/lib/python3.8/site-packages (from packaging>=20.0->transformers) (3.0.9)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->transformers) (2019.11.28)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests->transformers) (2.8)\n",
            "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->transformers) (1.25.8)\n",
            "Requirement already satisfied: charset-normalizer<3,>=2 in /home/nihar/.local/lib/python3.8/site-packages (from requests->transformers) (2.1.0)\n",
            "Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/nihar/.local/lib/python3.8/site-packages (from huggingface-hub<1.0,>=0.1.0->transformers) (4.3.0)\n",
            "Note: you may need to restart the kernel to use updated packages.\n"
          ]
        }
      ],
      "source": [
        "%pip install transformers"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "dqk4F9yJbK02",
        "outputId": "664aff21-08cb-4853-8915-3f6f0a85f1b1"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Requirement already satisfied: streamlit in /home/nihar/.local/lib/python3.8/site-packages (1.12.0)\n",
            "Requirement already satisfied: python-dateutil in /home/nihar/.local/lib/python3.8/site-packages (from streamlit) (2.8.2)\n",
            "Requirement already satisfied: altair>=3.2.0 in /home/nihar/.local/lib/python3.8/site-packages (from streamlit) (4.2.0)\n",
            "Requirement already satisfied: numpy in /home/nihar/.local/lib/python3.8/site-packages (from streamlit) (1.23.2)\n",
            "Requirement already satisfied: pandas>=0.21.0 in /home/nihar/.local/lib/python3.8/site-packages (from streamlit) (1.4.3)\n",
            "Requirement already satisfied: requests>=2.4 in /home/nihar/.local/lib/python3.8/site-packages (from streamlit) (2.28.1)\n",
            "Requirement already satisfied: click>=7.0 in /usr/lib/python3/dist-packages (from streamlit) (7.0)\n",
            "Requirement already satisfied: pydeck>=0.1.dev5 in /home/nihar/.local/lib/python3.8/site-packages (from streamlit) (0.7.1)\n",
            "Requirement already satisfied: gitpython!=3.1.19 in /home/nihar/.local/lib/python3.8/site-packages (from streamlit) (3.1.27)\n",
            "Requirement already satisfied: pillow>=6.2.0 in /usr/lib/python3/dist-packages (from streamlit) (7.0.0)\n",
            "Requirement already satisfied: semver in /home/nihar/.local/lib/python3.8/site-packages (from streamlit) (2.13.0)\n",
            "Requirement already satisfied: watchdog; platform_system != \"Darwin\" in /home/nihar/.local/lib/python3.8/site-packages (from streamlit) (2.1.9)\n",
            "Requirement already satisfied: pympler>=0.9 in /home/nihar/.local/lib/python3.8/site-packages (from streamlit) (1.0.1)\n",
            "Requirement already satisfied: blinker>=1.0.0 in /usr/lib/python3/dist-packages (from streamlit) (1.4)\n",
            "Requirement already satisfied: importlib-metadata>=1.4 in /home/nihar/.local/lib/python3.8/site-packages (from streamlit) (4.12.0)\n",
            "Requirement already satisfied: typing-extensions>=3.10.0.0 in /home/nihar/.local/lib/python3.8/site-packages (from streamlit) (4.3.0)\n",
            "Requirement already satisfied: protobuf<4,>=3.12 in /home/nihar/.local/lib/python3.8/site-packages (from streamlit) (3.19.4)\n",
            "Requirement already satisfied: tornado>=5.0 in /home/nihar/.local/lib/python3.8/site-packages (from streamlit) (6.2)\n",
            "Requirement already satisfied: rich>=10.11.0 in /home/nihar/.local/lib/python3.8/site-packages (from streamlit) (12.5.1)\n",
            "Requirement already satisfied: pyarrow>=4.0 in /home/nihar/.local/lib/python3.8/site-packages (from streamlit) (9.0.0)\n",
            "Requirement already satisfied: tzlocal>=1.1 in /home/nihar/.local/lib/python3.8/site-packages (from streamlit) (4.2)\n",
            "Requirement already satisfied: validators>=0.2 in /home/nihar/.local/lib/python3.8/site-packages (from streamlit) (0.20.0)\n",
            "Requirement already satisfied: toml in /home/nihar/.local/lib/python3.8/site-packages (from streamlit) (0.10.2)\n",
            "Requirement already satisfied: packaging>=14.1 in /home/nihar/.local/lib/python3.8/site-packages (from streamlit) (21.3)\n",
            "Requirement already satisfied: cachetools>=4.0 in /home/nihar/.local/lib/python3.8/site-packages (from streamlit) (5.2.0)\n",
            "Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil->streamlit) (1.14.0)\n",
            "Requirement already satisfied: toolz in /home/nihar/.local/lib/python3.8/site-packages (from altair>=3.2.0->streamlit) (0.12.0)\n",
            "Requirement already satisfied: jsonschema>=3.0 in /home/nihar/.local/lib/python3.8/site-packages (from altair>=3.2.0->streamlit) (4.13.0)\n",
            "Requirement already satisfied: entrypoints in /usr/lib/python3/dist-packages (from altair>=3.2.0->streamlit) (0.3)\n",
            "Requirement already satisfied: jinja2 in /home/nihar/.local/lib/python3.8/site-packages (from altair>=3.2.0->streamlit) (3.1.2)\n",
            "Requirement already satisfied: pytz>=2020.1 in /home/nihar/.local/lib/python3.8/site-packages (from pandas>=0.21.0->streamlit) (2022.2.1)\n",
            "Requirement already satisfied: charset-normalizer<3,>=2 in /home/nihar/.local/lib/python3.8/site-packages (from requests>=2.4->streamlit) (2.1.0)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.4->streamlit) (2019.11.28)\n",
            "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests>=2.4->streamlit) (1.25.8)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.4->streamlit) (2.8)\n",
            "Requirement already satisfied: ipywidgets>=7.0.0 in /home/nihar/.local/lib/python3.8/site-packages (from pydeck>=0.1.dev5->streamlit) (8.0.1)\n",
            "Requirement already satisfied: traitlets>=4.3.2 in /home/nihar/.local/lib/python3.8/site-packages (from pydeck>=0.1.dev5->streamlit) (5.3.0)\n",
            "Requirement already satisfied: ipykernel>=5.1.2; python_version >= \"3.4\" in /home/nihar/.local/lib/python3.8/site-packages (from pydeck>=0.1.dev5->streamlit) (6.15.1)\n",
            "Requirement already satisfied: gitdb<5,>=4.0.1 in /home/nihar/.local/lib/python3.8/site-packages (from gitpython!=3.1.19->streamlit) (4.0.9)\n",
            "Requirement already satisfied: zipp>=0.5 in /home/nihar/.local/lib/python3.8/site-packages (from importlib-metadata>=1.4->streamlit) (3.8.1)\n",
            "Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /home/nihar/.local/lib/python3.8/site-packages (from rich>=10.11.0->streamlit) (2.13.0)\n",
            "Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /home/nihar/.local/lib/python3.8/site-packages (from rich>=10.11.0->streamlit) (0.9.1)\n",
            "Requirement already satisfied: backports.zoneinfo; python_version < \"3.9\" in /home/nihar/.local/lib/python3.8/site-packages (from tzlocal>=1.1->streamlit) (0.2.1)\n",
            "Requirement already satisfied: pytz-deprecation-shim in /home/nihar/.local/lib/python3.8/site-packages (from tzlocal>=1.1->streamlit) (0.1.0.post0)\n",
            "Requirement already satisfied: decorator>=3.4.0 in /home/nihar/.local/lib/python3.8/site-packages (from validators>=0.2->streamlit) (5.1.1)\n",
            "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/nihar/.local/lib/python3.8/site-packages (from packaging>=14.1->streamlit) (3.0.9)\n",
            "Requirement already satisfied: importlib-resources>=1.4.0; python_version < \"3.9\" in /home/nihar/.local/lib/python3.8/site-packages (from jsonschema>=3.0->altair>=3.2.0->streamlit) (5.9.0)\n",
            "Requirement already satisfied: pkgutil-resolve-name>=1.3.10; python_version < \"3.9\" in /home/nihar/.local/lib/python3.8/site-packages (from jsonschema>=3.0->altair>=3.2.0->streamlit) (1.3.10)\n",
            "Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /home/nihar/.local/lib/python3.8/site-packages (from jsonschema>=3.0->altair>=3.2.0->streamlit) (0.18.1)\n",
            "Requirement already satisfied: attrs>=17.4.0 in /home/nihar/.local/lib/python3.8/site-packages (from jsonschema>=3.0->altair>=3.2.0->streamlit) (22.1.0)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /home/nihar/.local/lib/python3.8/site-packages (from jinja2->altair>=3.2.0->streamlit) (2.1.1)\n",
            "Requirement already satisfied: ipython>=6.1.0 in /home/nihar/.local/lib/python3.8/site-packages (from ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (8.4.0)\n",
            "Requirement already satisfied: widgetsnbextension~=4.0 in /home/nihar/.local/lib/python3.8/site-packages (from ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (4.0.1)\n",
            "Requirement already satisfied: jupyterlab-widgets~=3.0 in /home/nihar/.local/lib/python3.8/site-packages (from ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (3.0.1)\n",
            "Requirement already satisfied: matplotlib-inline>=0.1 in /home/nihar/.local/lib/python3.8/site-packages (from ipykernel>=5.1.2; python_version >= \"3.4\"->pydeck>=0.1.dev5->streamlit) (0.1.6)\n",
            "Requirement already satisfied: psutil in /home/nihar/.local/lib/python3.8/site-packages (from ipykernel>=5.1.2; python_version >= \"3.4\"->pydeck>=0.1.dev5->streamlit) (5.9.1)\n",
            "Requirement already satisfied: debugpy>=1.0 in /home/nihar/.local/lib/python3.8/site-packages (from ipykernel>=5.1.2; python_version >= \"3.4\"->pydeck>=0.1.dev5->streamlit) (1.6.3)\n",
            "Requirement already satisfied: pyzmq>=17 in /home/nihar/.local/lib/python3.8/site-packages (from ipykernel>=5.1.2; python_version >= \"3.4\"->pydeck>=0.1.dev5->streamlit) (23.2.1)\n",
            "Requirement already satisfied: jupyter-client>=6.1.12 in /home/nihar/.local/lib/python3.8/site-packages (from ipykernel>=5.1.2; python_version >= \"3.4\"->pydeck>=0.1.dev5->streamlit) (7.3.4)\n",
            "Requirement already satisfied: nest-asyncio in /home/nihar/.local/lib/python3.8/site-packages (from ipykernel>=5.1.2; python_version >= \"3.4\"->pydeck>=0.1.dev5->streamlit) (1.5.5)\n",
            "Requirement already satisfied: smmap<6,>=3.0.1 in /home/nihar/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19->streamlit) (5.0.0)\n",
            "Requirement already satisfied: tzdata; python_version >= \"3.6\" in /home/nihar/.local/lib/python3.8/site-packages (from pytz-deprecation-shim->tzlocal>=1.1->streamlit) (2022.2)\n",
            "Requirement already satisfied: pickleshare in /home/nihar/.local/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (0.7.5)\n",
            "Requirement already satisfied: backcall in /home/nihar/.local/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (0.2.0)\n",
            "Requirement already satisfied: pexpect>4.3; sys_platform != \"win32\" in /usr/lib/python3/dist-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (4.6.0)\n",
            "Requirement already satisfied: stack-data in /home/nihar/.local/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (0.4.0)\n",
            "Requirement already satisfied: jedi>=0.16 in /home/nihar/.local/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (0.18.1)\n",
            "Requirement already satisfied: setuptools>=18.5 in /usr/lib/python3/dist-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (45.2.0)\n",
            "Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /home/nihar/.local/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (3.0.30)\n",
            "Requirement already satisfied: jupyter-core>=4.9.2 in /home/nihar/.local/lib/python3.8/site-packages (from jupyter-client>=6.1.12->ipykernel>=5.1.2; python_version >= \"3.4\"->pydeck>=0.1.dev5->streamlit) (4.11.1)\n",
            "Requirement already satisfied: pure-eval in /home/nihar/.local/lib/python3.8/site-packages (from stack-data->ipython>=6.1.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (0.2.2)\n",
            "Requirement already satisfied: asttokens in /home/nihar/.local/lib/python3.8/site-packages (from stack-data->ipython>=6.1.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (2.0.8)\n",
            "Requirement already satisfied: executing in /home/nihar/.local/lib/python3.8/site-packages (from stack-data->ipython>=6.1.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (0.10.0)\n",
            "Requirement already satisfied: parso<0.9.0,>=0.8.0 in /home/nihar/.local/lib/python3.8/site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (0.8.3)\n",
            "Requirement already satisfied: wcwidth in /home/nihar/.local/lib/python3.8/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=6.1.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (0.2.5)\n",
            "Note: you may need to restart the kernel to use updated packages.\n"
          ]
        }
      ],
      "source": [
        "%pip install streamlit"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "2DfrFxutbM4G",
        "outputId": "8d4eb831-1e06-42bc-8efd-607b631c08d4"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Requirement already satisfied: pandas in /home/nihar/.local/lib/python3.8/site-packages (1.4.3)\n",
            "Requirement already satisfied: python-dateutil>=2.8.1 in /home/nihar/.local/lib/python3.8/site-packages (from pandas) (2.8.2)\n",
            "Requirement already satisfied: numpy>=1.18.5; platform_machine != \"aarch64\" and platform_machine != \"arm64\" and python_version < \"3.10\" in /home/nihar/.local/lib/python3.8/site-packages (from pandas) (1.23.2)\n",
            "Requirement already satisfied: pytz>=2020.1 in /home/nihar/.local/lib/python3.8/site-packages (from pandas) (2022.2.1)\n",
            "Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.1->pandas) (1.14.0)\n",
            "Note: you may need to restart the kernel to use updated packages.\n"
          ]
        }
      ],
      "source": [
        "%pip install pandas"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "J7U13F3CbQDg",
        "outputId": "20eb4d0b-af58-4973-c2a3-b265b9e80d88"
      },
      "outputs": [
        {
          "name": "stderr",
          "output_type": "stream",
          "text": [
            "2022-08-19 22:45:32.604010: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
            "2022-08-19 22:45:32.604034: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n"
          ]
        }
      ],
      "source": [
        "import tweepy as tw\n",
        "import streamlit as st\n",
        "import pandas as pd\n",
        "from transformers import pipeline"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "id": "FcB90LZpnXJQ"
      },
      "outputs": [],
      "source": [
        "Creating connection between app and twitter"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "id": "BhM87O_Kbwot"
      },
      "outputs": [],
      "source": [
        "consumer_key = 'v3flA8wrDiLaRkXwiN6I9QoLN'\n",
        "consumer_secret = 'Os6nmO62EfVPcWDrK0JmQvWYYIDAf5lNqaYKEtBSdCHHpwcadB'\n",
        "access_token = '1269160779904806920-pigIL0WP9uFjQ43cImncVwkANllPVs'\n",
        "access_token_secret = 'pArVvx871PSq4dhvDHvXOECojRwkpovaoUPYYgTmLWlU9'\n",
        "auth = tw.OAuthHandler(consumer_key,consumer_secret)\n",
        "auth.set_access_token(access_token,access_token_secret)\n",
        "api = tw.API(auth,wait_on_rate_limit=True)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Requirement already satisfied: tensorflow in /home/nihar/.local/lib/python3.8/site-packages (2.9.1)\n",
            "Requirement already satisfied: packaging in /home/nihar/.local/lib/python3.8/site-packages (from tensorflow) (21.3)\n",
            "Requirement already satisfied: absl-py>=1.0.0 in /home/nihar/.local/lib/python3.8/site-packages (from tensorflow) (1.2.0)\n",
            "Requirement already satisfied: flatbuffers<2,>=1.12 in /home/nihar/.local/lib/python3.8/site-packages (from tensorflow) (1.12)\n",
            "Requirement already satisfied: astunparse>=1.6.0 in /home/nihar/.local/lib/python3.8/site-packages (from tensorflow) (1.6.3)\n",
            "Requirement already satisfied: google-pasta>=0.1.1 in /home/nihar/.local/lib/python3.8/site-packages (from tensorflow) (0.2.0)\n",
            "Requirement already satisfied: typing-extensions>=3.6.6 in /home/nihar/.local/lib/python3.8/site-packages (from tensorflow) (4.3.0)\n",
            "Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/nihar/.local/lib/python3.8/site-packages (from tensorflow) (1.47.0)\n",
            "Requirement already satisfied: tensorflow-estimator<2.10.0,>=2.9.0rc0 in /home/nihar/.local/lib/python3.8/site-packages (from tensorflow) (2.9.0)\n",
            "Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /home/nihar/.local/lib/python3.8/site-packages (from tensorflow) (0.4.0)\n",
            "Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from tensorflow) (45.2.0)\n",
            "Requirement already satisfied: protobuf<3.20,>=3.9.2 in /home/nihar/.local/lib/python3.8/site-packages (from tensorflow) (3.19.4)\n",
            "Requirement already satisfied: opt-einsum>=2.3.2 in /home/nihar/.local/lib/python3.8/site-packages (from tensorflow) (3.3.0)\n",
            "Requirement already satisfied: numpy>=1.20 in /home/nihar/.local/lib/python3.8/site-packages (from tensorflow) (1.23.2)\n",
            "Requirement already satisfied: wrapt>=1.11.0 in /home/nihar/.local/lib/python3.8/site-packages (from tensorflow) (1.14.1)\n",
            "Requirement already satisfied: libclang>=13.0.0 in /home/nihar/.local/lib/python3.8/site-packages (from tensorflow) (14.0.6)\n",
            "Requirement already satisfied: termcolor>=1.1.0 in /home/nihar/.local/lib/python3.8/site-packages (from tensorflow) (1.1.0)\n",
            "Requirement already satisfied: six>=1.12.0 in /usr/lib/python3/dist-packages (from tensorflow) (1.14.0)\n",
            "Requirement already satisfied: keras-preprocessing>=1.1.1 in /home/nihar/.local/lib/python3.8/site-packages (from tensorflow) (1.1.2)\n",
            "Requirement already satisfied: tensorboard<2.10,>=2.9 in /home/nihar/.local/lib/python3.8/site-packages (from tensorflow) (2.9.1)\n",
            "Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /home/nihar/.local/lib/python3.8/site-packages (from tensorflow) (0.26.0)\n",
            "Requirement already satisfied: keras<2.10.0,>=2.9.0rc0 in /home/nihar/.local/lib/python3.8/site-packages (from tensorflow) (2.9.0)\n",
            "Requirement already satisfied: h5py>=2.9.0 in /home/nihar/.local/lib/python3.8/site-packages (from tensorflow) (3.7.0)\n",
            "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/nihar/.local/lib/python3.8/site-packages (from packaging->tensorflow) (3.0.9)\n",
            "Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/lib/python3/dist-packages (from astunparse>=1.6.0->tensorflow) (0.34.2)\n",
            "Requirement already satisfied: google-auth<3,>=1.6.3 in /home/nihar/.local/lib/python3.8/site-packages (from tensorboard<2.10,>=2.9->tensorflow) (2.10.0)\n",
            "Requirement already satisfied: requests<3,>=2.21.0 in /home/nihar/.local/lib/python3.8/site-packages (from tensorboard<2.10,>=2.9->tensorflow) (2.28.1)\n",
            "Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /home/nihar/.local/lib/python3.8/site-packages (from tensorboard<2.10,>=2.9->tensorflow) (0.4.6)\n",
            "Requirement already satisfied: werkzeug>=1.0.1 in /home/nihar/.local/lib/python3.8/site-packages (from tensorboard<2.10,>=2.9->tensorflow) (2.2.2)\n",
            "Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /home/nihar/.local/lib/python3.8/site-packages (from tensorboard<2.10,>=2.9->tensorflow) (0.6.1)\n",
            "Requirement already satisfied: markdown>=2.6.8 in /home/nihar/.local/lib/python3.8/site-packages (from tensorboard<2.10,>=2.9->tensorflow) (3.4.1)\n",
            "Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /home/nihar/.local/lib/python3.8/site-packages (from tensorboard<2.10,>=2.9->tensorflow) (1.8.1)\n",
            "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/nihar/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow) (5.2.0)\n",
            "Requirement already satisfied: rsa<5,>=3.1.4; python_version >= \"3.6\" in /home/nihar/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow) (4.9)\n",
            "Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/nihar/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow) (0.2.8)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow) (2.8)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow) (2019.11.28)\n",
            "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow) (1.25.8)\n",
            "Requirement already satisfied: charset-normalizer<3,>=2 in /home/nihar/.local/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow) (2.1.0)\n",
            "Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/nihar/.local/lib/python3.8/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.10,>=2.9->tensorflow) (1.3.1)\n",
            "Requirement already satisfied: MarkupSafe>=2.1.1 in /home/nihar/.local/lib/python3.8/site-packages (from werkzeug>=1.0.1->tensorboard<2.10,>=2.9->tensorflow) (2.1.1)\n",
            "Requirement already satisfied: importlib-metadata>=4.4; python_version < \"3.10\" in /home/nihar/.local/lib/python3.8/site-packages (from markdown>=2.6.8->tensorboard<2.10,>=2.9->tensorflow) (4.12.0)\n",
            "Requirement already satisfied: pyasn1>=0.1.3 in /home/nihar/.local/lib/python3.8/site-packages (from rsa<5,>=3.1.4; python_version >= \"3.6\"->google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow) (0.4.8)\n",
            "Requirement already satisfied: oauthlib>=3.0.0 in /home/nihar/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.10,>=2.9->tensorflow) (3.2.0)\n",
            "Requirement already satisfied: zipp>=0.5 in /home/nihar/.local/lib/python3.8/site-packages (from importlib-metadata>=4.4; python_version < \"3.10\"->markdown>=2.6.8->tensorboard<2.10,>=2.9->tensorflow) (3.8.1)\n",
            "Note: you may need to restart the kernel to use updated packages.\n"
          ]
        }
      ],
      "source": [
        "%pip install tensorflow"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 312,
          "referenced_widgets": [
            "a6e98c1178394f49ade4991cd36d91e5",
            "9dd4bfb26327416db139e341173b33ce",
            "2fb6a0520e3b4860a078e84c46638dcc",
            "6d7cd3a5c81e4f09a06fd2ede5157fde",
            "f2d22145a90947e1bfa8d00ab6f2e266",
            "a76ffcbe35f14e70bb3e564ce2e651f1",
            "e066e18f1b564c56b78ad735773c3c64",
            "62e6e5072aa74079a6bea703c212ee85",
            "a708949dcff34d15ad1b502789ba7d8e",
            "d77d96939ba8436d8b66851d29ee64db",
            "f0e7c66148a04caabdc8bff32f55453e",
            "93e23aef99bf4b25b36e8f76b5c66bb0",
            "0d8fc463fc63429894cc71b819f1b5be",
            "defa57507bd941789859dc7fc7480892",
            "82eb6030d60c46d180076b1f439c3284",
            "efd5eee6ecf0435fb302c941cc80e7ff",
            "944619b1fade4e26a7c432ae5c318285",
            "a38800fc1a5b4bff865976d7b9a9902a",
            "6bdd2c9fb05344aeaf017991219ae69b",
            "d20627e707184f27b668fcbd35900acb",
            "b2f49d253ddb4e1d9e686cec22e823e7",
            "2ee106a7b1e943cb9bec3963f8e34e90",
            "13267c27f1b24b40a8370a13c983b95c",
            "17be7ec9a01243498e69083653bc18df",
            "58a4ead8386a4e3ebb3342772c192a1f",
            "a46bd22b94b143d9b61d4bd66a8dda13",
            "da3f495c55084fcd9880d75b60727d90",
            "00fdd30155f54325b96ee3f32dbc2e98",
            "2aa8ef3ded8a4fb88c939d59b4c3cdb2",
            "884c9a88a2eb4317a059054fbb655616",
            "cb8d8734c1e745c88b9ee250bc05f71c",
            "2f88de03b14240288feb8e0894d3c1fe",
            "9191cbea461245dcabda3a46a1f8d73c",
            "ca689be81b3a4596afe25fee6558d34b",
            "aee80ed376024779967d16a7b5e9ec3f",
            "20af89563da74586b1b5986abeb9e0a8",
            "440c1444f4c24d50b696b4b58cb74198",
            "2313cda03aca4572915718d8c54d1ebb",
            "43f51173e1c14145aa05302a9d5ce991",
            "0700555de0704e45a50f023d66498439",
            "c36b4b70717f414eb6e25e879d9621d9",
            "86e3b1481436471d84c7c1ff2f7f22de",
            "9ab47e38b76b4a5f86ea28b73d76d08a",
            "1a7f5ed8aa9c43a29ae5e8e39e97e270"
          ]
        },
        "id": "e6_rwBPnnRne",
        "outputId": "b0136b97-b1bd-4a72-b111-05c49cc4f759"
      },
      "outputs": [
        {
          "name": "stderr",
          "output_type": "stream",
          "text": [
            "No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).\n",
            "Using a pipeline without specifying a model name and revision in production is not recommended.\n",
            "2022-08-19 22:45:50.539679: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
            "2022-08-19 22:45:50.539720: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Jarviss): /proc/driver/nvidia/version does not exist\n",
            "2022-08-19 22:45:50.540112: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
            "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "2022-08-19 22:45:50.595367: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 93763584 exceeds 10% of free system memory.\n",
            "2022-08-19 22:45:50.694857: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 93763584 exceeds 10% of free system memory.\n",
            "2022-08-19 22:45:50.725742: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 93763584 exceeds 10% of free system memory.\n",
            "2022-08-19 22:45:58.881852: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 93763584 exceeds 10% of free system memory.\n",
            "2022-08-19 22:45:58.943982: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 93763584 exceeds 10% of free system memory.\n",
            "All model checkpoint layers were used when initializing TFDistilBertForSequenceClassification.\n",
            "\n",
            "All the layers of TFDistilBertForSequenceClassification were initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english.\n",
            "If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.\n"
          ]
        }
      ],
      "source": [
        "classifier = pipeline('sentiment-analysis')"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "id": "2RdDe6aSnwl_"
      },
      "outputs": [],
      "source": [
        "Give name to app using streamlit"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "uRxOp5ACnj1i",
        "outputId": "e1c122d9-9f7c-4584-a6a2-51613f319dce"
      },
      "outputs": [
        {
          "data": {
            "text/plain": [
              "DeltaGenerator(_root_container=0, _provided_cursor=None, _parent=None, _block_type=None, _form_data=FormData(form_id='Virat'))"
            ]
          },
          "execution_count": 12,
          "metadata": {},
          "output_type": "execute_result"
        }
      ],
      "source": [
        "st.title('Tweets sentiment Analysis using Tweepy and huggingface analysis')\n",
        "st.markdown('This app uses tweepy to get tweets from twitter based on the input name/phrase.It then processes the tweets through HuggingFace transformers pipeline function for sentiment analysis. The resulting sentiments and corresponding tweets are then put in a dataframe for display which is what you see as result.')"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "id": "K3iDM9lkoThw"
      },
      "outputs": [],
      "source": [
        "def run():\n",
        "  with st.form(key='Virat'):\n",
        "    search_words = st.text_input('cricket')\n",
        "    number_of_tweets = st.number_input('45')\n",
        "    submit_button = st.form_submit_button(label='Submit')\n",
        "  if submit_button:\n",
        "    tweets =tw.Cursor(api.search_tweets,q=search_words,lang=\"en\").items(number_of_tweets)\n",
        "    tweet_list = [i.text for i in tweets]\n",
        "    p = [i for i in classifier(tweet_list)]\n",
        "    q=[p[i]['label'] for i in range(len(p))]\n",
        "    df = pd.DataFrame(list(zip(tweet_list, q)),columns =['Latest'+str(number_of_tweets)+'Tweets'+'on'+search_words, 'sentiment'])\n",
        "    st.write(df)\n",
        " \n",
        "\n",
        "if __name__=='__main__':\n",
        "  run()"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "id": "8rIMnekckGzv"
      },
      "outputs": [],
      "source": []
    }
  ],
  "metadata": {
    "colab": {
      "collapsed_sections": [],
      "name": "Live_Tweets.py",
      "provenance": []
    },
    "kernelspec": {
      "display_name": "Python 3.8.10 64-bit",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.8.10"
    },
    "vscode": {
      "interpreter": {
        "hash": "916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1"
      }
    },
    "widgets": {
      "application/vnd.jupyter.widget-state+json": {
        "00fdd30155f54325b96ee3f32dbc2e98": {
          "model_module": "@jupyter-widgets/base",
          "model_module_version": "1.2.0",
          "model_name": "LayoutModel",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": None,
            "align_items": None,
            "align_self": None,
            "border": None,
            "bottom": None,
            "display": None,
            "flex": None,
            "flex_flow": None,
            "grid_area": None,
            "grid_auto_columns": None,
            "grid_auto_flow": None,
            "grid_auto_rows": None,
            "grid_column": None,
            "grid_gap": None,
            "grid_row": None,
            "grid_template_areas": None,
            "grid_template_columns": None,
            "grid_template_rows": None,
            "height": None,
            "justify_content": None,
            "justify_items": None,
            "left": None,
            "margin": None,
            "max_height": None,
            "max_width": None,
            "min_height": None,
            "min_width": None,
            "object_fit": None,
            "object_position": None,
            "order": None,
            "overflow": None,
            "overflow_x": None,
            "overflow_y": None,
            "padding": None,
            "right": None,
            "top": None,
            "visibility": None,
            "width": None
          }
        },
        "0700555de0704e45a50f023d66498439": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "DescriptionStyleModel",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "0d8fc463fc63429894cc71b819f1b5be": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "HTMLModel",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HTMLModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HTMLView",
            "description": "",
            "description_tooltip": None,
            "layout": "IPY_MODEL_944619b1fade4e26a7c432ae5c318285",
            "placeholder": "​",
            "style": "IPY_MODEL_a38800fc1a5b4bff865976d7b9a9902a",
            "value": "Downloading pytorch_model.bin: 100%"
          }
        },
        "13267c27f1b24b40a8370a13c983b95c": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "HBoxModel",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HBoxModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HBoxView",
            "box_style": "",
            "children": [
              "IPY_MODEL_17be7ec9a01243498e69083653bc18df",
              "IPY_MODEL_58a4ead8386a4e3ebb3342772c192a1f",
              "IPY_MODEL_a46bd22b94b143d9b61d4bd66a8dda13"
            ],
            "layout": "IPY_MODEL_da3f495c55084fcd9880d75b60727d90"
          }
        },
        "17be7ec9a01243498e69083653bc18df": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "HTMLModel",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HTMLModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HTMLView",
            "description": "",
            "description_tooltip": None,
            "layout": "IPY_MODEL_00fdd30155f54325b96ee3f32dbc2e98",
            "placeholder": "​",
            "style": "IPY_MODEL_2aa8ef3ded8a4fb88c939d59b4c3cdb2",
            "value": "Downloading tokenizer_config.json: 100%"
          }
        },
        "1a7f5ed8aa9c43a29ae5e8e39e97e270": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "DescriptionStyleModel",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "20af89563da74586b1b5986abeb9e0a8": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "FloatProgressModel",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "FloatProgressModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "ProgressView",
            "bar_style": "success",
            "description": "",
            "description_tooltip": None,
            "layout": "IPY_MODEL_c36b4b70717f414eb6e25e879d9621d9",
            "max": 231508,
            "min": 0,
            "orientation": "horizontal",
            "style": "IPY_MODEL_86e3b1481436471d84c7c1ff2f7f22de",
            "value": 231508
          }
        },
        "2313cda03aca4572915718d8c54d1ebb": {
          "model_module": "@jupyter-widgets/base",
          "model_module_version": "1.2.0",
          "model_name": "LayoutModel",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": None,
            "align_items": None,
            "align_self": None,
            "border": None,
            "bottom": None,
            "display": None,
            "flex": None,
            "flex_flow": None,
            "grid_area": None,
            "grid_auto_columns": None,
            "grid_auto_flow": None,
            "grid_auto_rows": None,
            "grid_column": None,
            "grid_gap": None,
            "grid_row": None,
            "grid_template_areas": None,
            "grid_template_columns": None,
            "grid_template_rows": None,
            "height": None,
            "justify_content": None,
            "justify_items": None,
            "left": None,
            "margin": None,
            "max_height": None,
            "max_width": None,
            "min_height": None,
            "min_width": None,
            "object_fit": None,
            "object_position": None,
            "order": None,
            "overflow": None,
            "overflow_x": None,
            "overflow_y": None,
            "padding": None,
            "right": None,
            "top": None,
            "visibility": None,
            "width": None
          }
        },
        "2aa8ef3ded8a4fb88c939d59b4c3cdb2": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "DescriptionStyleModel",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "2ee106a7b1e943cb9bec3963f8e34e90": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "DescriptionStyleModel",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "2f88de03b14240288feb8e0894d3c1fe": {
          "model_module": "@jupyter-widgets/base",
          "model_module_version": "1.2.0",
          "model_name": "LayoutModel",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": None,
            "align_items": None,
            "align_self": None,
            "border": None,
            "bottom": None,
            "display": None,
            "flex": None,
            "flex_flow": None,
            "grid_area": None,
            "grid_auto_columns": None,
            "grid_auto_flow": None,
            "grid_auto_rows": None,
            "grid_column": None,
            "grid_gap": None,
            "grid_row": None,
            "grid_template_areas": None,
            "grid_template_columns": None,
            "grid_template_rows": None,
            "height": None,
            "justify_content": None,
            "justify_items": None,
            "left": None,
            "margin": None,
            "max_height": None,
            "max_width": None,
            "min_height": None,
            "min_width": None,
            "object_fit": None,
            "object_position": None,
            "order": None,
            "overflow": None,
            "overflow_x": None,
            "overflow_y": None,
            "padding": None,
            "right": None,
            "top": None,
            "visibility": None,
            "width": None
          }
        },
        "2fb6a0520e3b4860a078e84c46638dcc": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "FloatProgressModel",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "FloatProgressModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "ProgressView",
            "bar_style": "success",
            "description": "",
            "description_tooltip": None,
            "layout": "IPY_MODEL_62e6e5072aa74079a6bea703c212ee85",
            "max": 629,
            "min": 0,
            "orientation": "horizontal",
            "style": "IPY_MODEL_a708949dcff34d15ad1b502789ba7d8e",
            "value": 629
          }
        },
        "43f51173e1c14145aa05302a9d5ce991": {
          "model_module": "@jupyter-widgets/base",
          "model_module_version": "1.2.0",
          "model_name": "LayoutModel",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": None,
            "align_items": None,
            "align_self": None,
            "border": None,
            "bottom": None,
            "display": None,
            "flex": None,
            "flex_flow": None,
            "grid_area": None,
            "grid_auto_columns": None,
            "grid_auto_flow": None,
            "grid_auto_rows": None,
            "grid_column": None,
            "grid_gap": None,
            "grid_row": None,
            "grid_template_areas": None,
            "grid_template_columns": None,
            "grid_template_rows": None,
            "height": None,
            "justify_content": None,
            "justify_items": None,
            "left": None,
            "margin": None,
            "max_height": None,
            "max_width": None,
            "min_height": None,
            "min_width": None,
            "object_fit": None,
            "object_position": None,
            "order": None,
            "overflow": None,
            "overflow_x": None,
            "overflow_y": None,
            "padding": None,
            "right": None,
            "top": None,
            "visibility": None,
            "width": None
          }
        },
        "440c1444f4c24d50b696b4b58cb74198": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "HTMLModel",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HTMLModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HTMLView",
            "description": "",
            "description_tooltip": None,
            "layout": "IPY_MODEL_9ab47e38b76b4a5f86ea28b73d76d08a",
            "placeholder": "​",
            "style": "IPY_MODEL_1a7f5ed8aa9c43a29ae5e8e39e97e270",
            "value": " 226k/226k [00:00&lt;00:00, 585kB/s]"
          }
        },
        "58a4ead8386a4e3ebb3342772c192a1f": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "FloatProgressModel",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "FloatProgressModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "ProgressView",
            "bar_style": "success",
            "description": "",
            "description_tooltip": None,
            "layout": "IPY_MODEL_884c9a88a2eb4317a059054fbb655616",
            "max": 48,
            "min": 0,
            "orientation": "horizontal",
            "style": "IPY_MODEL_cb8d8734c1e745c88b9ee250bc05f71c",
            "value": 48
          }
        },
        "62e6e5072aa74079a6bea703c212ee85": {
          "model_module": "@jupyter-widgets/base",
          "model_module_version": "1.2.0",
          "model_name": "LayoutModel",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": None,
            "align_items": None,
            "align_self": None,
            "border": None,
            "bottom": None,
            "display": None,
            "flex": None,
            "flex_flow": None,
            "grid_area": None,
            "grid_auto_columns": None,
            "grid_auto_flow": None,
            "grid_auto_rows": None,
            "grid_column": None,
            "grid_gap": None,
            "grid_row": None,
            "grid_template_areas": None,
            "grid_template_columns": None,
            "grid_template_rows": None,
            "height": None,
            "justify_content": None,
            "justify_items": None,
            "left": None,
            "margin": None,
            "max_height": None,
            "max_width": None,
            "min_height": None,
            "min_width": None,
            "object_fit": None,
            "object_position": None,
            "order": None,
            "overflow": None,
            "overflow_x": None,
            "overflow_y": None,
            "padding": None,
            "right": None,
            "top": None,
            "visibility": None,
            "width": None
          }
        },
        "6bdd2c9fb05344aeaf017991219ae69b": {
          "model_module": "@jupyter-widgets/base",
          "model_module_version": "1.2.0",
          "model_name": "LayoutModel",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": None,
            "align_items": None,
            "align_self": None,
            "border": None,
            "bottom": None,
            "display": None,
            "flex": None,
            "flex_flow": None,
            "grid_area": None,
            "grid_auto_columns": None,
            "grid_auto_flow": None,
            "grid_auto_rows": None,
            "grid_column": None,
            "grid_gap": None,
            "grid_row": None,
            "grid_template_areas": None,
            "grid_template_columns": None,
            "grid_template_rows": None,
            "height": None,
            "justify_content": None,
            "justify_items": None,
            "left": None,
            "margin": None,
            "max_height": None,
            "max_width": None,
            "min_height": None,
            "min_width": None,
            "object_fit": None,
            "object_position": None,
            "order": None,
            "overflow": None,
            "overflow_x": None,
            "overflow_y": None,
            "padding": None,
            "right": None,
            "top": None,
            "visibility": None,
            "width": None
          }
        },
        "6d7cd3a5c81e4f09a06fd2ede5157fde": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "HTMLModel",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HTMLModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HTMLView",
            "description": "",
            "description_tooltip": None,
            "layout": "IPY_MODEL_d77d96939ba8436d8b66851d29ee64db",
            "placeholder": "​",
            "style": "IPY_MODEL_f0e7c66148a04caabdc8bff32f55453e",
            "value": " 629/629 [00:00&lt;00:00, 18.4kB/s]"
          }
        },
        "82eb6030d60c46d180076b1f439c3284": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "HTMLModel",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HTMLModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HTMLView",
            "description": "",
            "description_tooltip": None,
            "layout": "IPY_MODEL_b2f49d253ddb4e1d9e686cec22e823e7",
            "placeholder": "​",
            "style": "IPY_MODEL_2ee106a7b1e943cb9bec3963f8e34e90",
            "value": " 255M/255M [00:05&lt;00:00, 46.0MB/s]"
          }
        },
        "86e3b1481436471d84c7c1ff2f7f22de": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "ProgressStyleModel",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ProgressStyleModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "bar_color": None,
            "description_width": ""
          }
        },
        "884c9a88a2eb4317a059054fbb655616": {
          "model_module": "@jupyter-widgets/base",
          "model_module_version": "1.2.0",
          "model_name": "LayoutModel",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": None,
            "align_items": None,
            "align_self": None,
            "border": None,
            "bottom": None,
            "display": None,
            "flex": None,
            "flex_flow": None,
            "grid_area": None,
            "grid_auto_columns": None,
            "grid_auto_flow": None,
            "grid_auto_rows": None,
            "grid_column": None,
            "grid_gap": None,
            "grid_row": None,
            "grid_template_areas": None,
            "grid_template_columns": None,
            "grid_template_rows": None,
            "height": None,
            "justify_content": None,
            "justify_items": None,
            "left": None,
            "margin": None,
            "max_height": None,
            "max_width": None,
            "min_height": None,
            "min_width": None,
            "object_fit": None,
            "object_position": None,
            "order": None,
            "overflow": None,
            "overflow_x": None,
            "overflow_y": None,
            "padding": None,
            "right": None,
            "top": None,
            "visibility": None,
            "width": None
          }
        },
        "9191cbea461245dcabda3a46a1f8d73c": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "DescriptionStyleModel",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "93e23aef99bf4b25b36e8f76b5c66bb0": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "HBoxModel",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HBoxModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HBoxView",
            "box_style": "",
            "children": [
              "IPY_MODEL_0d8fc463fc63429894cc71b819f1b5be",
              "IPY_MODEL_defa57507bd941789859dc7fc7480892",
              "IPY_MODEL_82eb6030d60c46d180076b1f439c3284"
            ],
            "layout": "IPY_MODEL_efd5eee6ecf0435fb302c941cc80e7ff"
          }
        },
        "944619b1fade4e26a7c432ae5c318285": {
          "model_module": "@jupyter-widgets/base",
          "model_module_version": "1.2.0",
          "model_name": "LayoutModel",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": None,
            "align_items": None,
            "align_self": None,
            "border": None,
            "bottom": None,
            "display": None,
            "flex": None,
            "flex_flow": None,
            "grid_area": None,
            "grid_auto_columns": None,
            "grid_auto_flow": None,
            "grid_auto_rows": None,
            "grid_column": None,
            "grid_gap": None,
            "grid_row": None,
            "grid_template_areas": None,
            "grid_template_columns": None,
            "grid_template_rows": None,
            "height": None,
            "justify_content": None,
            "justify_items": None,
            "left": None,
            "margin": None,
            "max_height": None,
            "max_width": None,
            "min_height": None,
            "min_width": None,
            "object_fit": None,
            "object_position": None,
            "order": None,
            "overflow": None,
            "overflow_x": None,
            "overflow_y": None,
            "padding": None,
            "right": None,
            "top": None,
            "visibility": None,
            "width": None
          }
        },
        "9ab47e38b76b4a5f86ea28b73d76d08a": {
          "model_module": "@jupyter-widgets/base",
          "model_module_version": "1.2.0",
          "model_name": "LayoutModel",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": None,
            "align_items": None,
            "align_self": None,
            "border": None,
            "bottom": None,
            "display": None,
            "flex": None,
            "flex_flow": None,
            "grid_area": None,
            "grid_auto_columns": None,
            "grid_auto_flow": None,
            "grid_auto_rows": None,
            "grid_column": None,
            "grid_gap": None,
            "grid_row": None,
            "grid_template_areas": None,
            "grid_template_columns": None,
            "grid_template_rows": None,
            "height": None,
            "justify_content": None,
            "justify_items": None,
            "left": None,
            "margin": None,
            "max_height": None,
            "max_width": None,
            "min_height": None,
            "min_width": None,
            "object_fit": None,
            "object_position": None,
            "order": None,
            "overflow": None,
            "overflow_x": None,
            "overflow_y": None,
            "padding": None,
            "right": None,
            "top": None,
            "visibility": None,
            "width": None
          }
        },
        "9dd4bfb26327416db139e341173b33ce": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "HTMLModel",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HTMLModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HTMLView",
            "description": "",
            "description_tooltip": None,
            "layout": "IPY_MODEL_a76ffcbe35f14e70bb3e564ce2e651f1",
            "placeholder": "​",
            "style": "IPY_MODEL_e066e18f1b564c56b78ad735773c3c64",
            "value": "Downloading config.json: 100%"
          }
        },
        "a38800fc1a5b4bff865976d7b9a9902a": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "DescriptionStyleModel",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "a46bd22b94b143d9b61d4bd66a8dda13": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "HTMLModel",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HTMLModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HTMLView",
            "description": "",
            "description_tooltip": None,
            "layout": "IPY_MODEL_2f88de03b14240288feb8e0894d3c1fe",
            "placeholder": "​",
            "style": "IPY_MODEL_9191cbea461245dcabda3a46a1f8d73c",
            "value": " 48.0/48.0 [00:00&lt;00:00, 1.30kB/s]"
          }
        },
        "a6e98c1178394f49ade4991cd36d91e5": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "HBoxModel",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HBoxModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HBoxView",
            "box_style": "",
            "children": [
              "IPY_MODEL_9dd4bfb26327416db139e341173b33ce",
              "IPY_MODEL_2fb6a0520e3b4860a078e84c46638dcc",
              "IPY_MODEL_6d7cd3a5c81e4f09a06fd2ede5157fde"
            ],
            "layout": "IPY_MODEL_f2d22145a90947e1bfa8d00ab6f2e266"
          }
        },
        "a708949dcff34d15ad1b502789ba7d8e": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "ProgressStyleModel",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ProgressStyleModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "bar_color": None,
            "description_width": ""
          }
        },
        "a76ffcbe35f14e70bb3e564ce2e651f1": {
          "model_module": "@jupyter-widgets/base",
          "model_module_version": "1.2.0",
          "model_name": "LayoutModel",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": None,
            "align_items": None,
            "align_self": None,
            "border": None,
            "bottom": None,
            "display": None,
            "flex": None,
            "flex_flow": None,
            "grid_area": None,
            "grid_auto_columns": None,
            "grid_auto_flow": None,
            "grid_auto_rows": None,
            "grid_column": None,
            "grid_gap": None,
            "grid_row": None,
            "grid_template_areas": None,
            "grid_template_columns": None,
            "grid_template_rows": None,
            "height": None,
            "justify_content": None,
            "justify_items": None,
            "left": None,
            "margin": None,
            "max_height": None,
            "max_width": None,
            "min_height": None,
            "min_width": None,
            "object_fit": None,
            "object_position": None,
            "order": None,
            "overflow": None,
            "overflow_x": None,
            "overflow_y": None,
            "padding": None,
            "right": None,
            "top": None,
            "visibility": None,
            "width": None
          }
        },
        "aee80ed376024779967d16a7b5e9ec3f": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "HTMLModel",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HTMLModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HTMLView",
            "description": "",
            "description_tooltip": None,
            "layout": "IPY_MODEL_43f51173e1c14145aa05302a9d5ce991",
            "placeholder": "​",
            "style": "IPY_MODEL_0700555de0704e45a50f023d66498439",
            "value": "Downloading vocab.txt: 100%"
          }
        },
        "b2f49d253ddb4e1d9e686cec22e823e7": {
          "model_module": "@jupyter-widgets/base",
          "model_module_version": "1.2.0",
          "model_name": "LayoutModel",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": None,
            "align_items": None,
            "align_self": None,
            "border": None,
            "bottom": None,
            "display": None,
            "flex": None,
            "flex_flow": None,
            "grid_area": None,
            "grid_auto_columns": None,
            "grid_auto_flow": None,
            "grid_auto_rows": None,
            "grid_column": None,
            "grid_gap": None,
            "grid_row": None,
            "grid_template_areas": None,
            "grid_template_columns": None,
            "grid_template_rows": None,
            "height": None,
            "justify_content": None,
            "justify_items": None,
            "left": None,
            "margin": None,
            "max_height": None,
            "max_width": None,
            "min_height": None,
            "min_width": None,
            "object_fit": None,
            "object_position": None,
            "order": None,
            "overflow": None,
            "overflow_x": None,
            "overflow_y": None,
            "padding": None,
            "right": None,
            "top": None,
            "visibility": None,
            "width": None
          }
        },
        "c36b4b70717f414eb6e25e879d9621d9": {
          "model_module": "@jupyter-widgets/base",
          "model_module_version": "1.2.0",
          "model_name": "LayoutModel",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": None,
            "align_items": None,
            "align_self": None,
            "border": None,
            "bottom": None,
            "display": None,
            "flex": None,
            "flex_flow": None,
            "grid_area": None,
            "grid_auto_columns": None,
            "grid_auto_flow": None,
            "grid_auto_rows": None,
            "grid_column": None,
            "grid_gap": None,
            "grid_row": None,
            "grid_template_areas": None,
            "grid_template_columns": None,
            "grid_template_rows": None,
            "height": None,
            "justify_content": None,
            "justify_items": None,
            "left": None,
            "margin": None,
            "max_height": None,
            "max_width": None,
            "min_height": None,
            "min_width": None,
            "object_fit": None,
            "object_position": None,
            "order": None,
            "overflow": None,
            "overflow_x": None,
            "overflow_y": None,
            "padding": None,
            "right": None,
            "top": None,
            "visibility": None,
            "width": None
          }
        },
        "ca689be81b3a4596afe25fee6558d34b": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "HBoxModel",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HBoxModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HBoxView",
            "box_style": "",
            "children": [
              "IPY_MODEL_aee80ed376024779967d16a7b5e9ec3f",
              "IPY_MODEL_20af89563da74586b1b5986abeb9e0a8",
              "IPY_MODEL_440c1444f4c24d50b696b4b58cb74198"
            ],
            "layout": "IPY_MODEL_2313cda03aca4572915718d8c54d1ebb"
          }
        },
        "cb8d8734c1e745c88b9ee250bc05f71c": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "ProgressStyleModel",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ProgressStyleModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "bar_color": None,
            "description_width": ""
          }
        },
        "d20627e707184f27b668fcbd35900acb": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "ProgressStyleModel",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ProgressStyleModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "bar_color": None,
            "description_width": ""
          }
        },
        "d77d96939ba8436d8b66851d29ee64db": {
          "model_module": "@jupyter-widgets/base",
          "model_module_version": "1.2.0",
          "model_name": "LayoutModel",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": None,
            "align_items": None,
            "align_self": None,
            "border": None,
            "bottom": None,
            "display": None,
            "flex": None,
            "flex_flow": None,
            "grid_area": None,
            "grid_auto_columns": None,
            "grid_auto_flow": None,
            "grid_auto_rows": None,
            "grid_column": None,
            "grid_gap": None,
            "grid_row": None,
            "grid_template_areas": None,
            "grid_template_columns": None,
            "grid_template_rows": None,
            "height": None,
            "justify_content": None,
            "justify_items": None,
            "left": None,
            "margin": None,
            "max_height": None,
            "max_width": None,
            "min_height": None,
            "min_width": None,
            "object_fit": None,
            "object_position": None,
            "order": None,
            "overflow": None,
            "overflow_x": None,
            "overflow_y": None,
            "padding": None,
            "right": None,
            "top": None,
            "visibility": None,
            "width": None
          }
        },
        "da3f495c55084fcd9880d75b60727d90": {
          "model_module": "@jupyter-widgets/base",
          "model_module_version": "1.2.0",
          "model_name": "LayoutModel",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": None,
            "align_items": None,
            "align_self": None,
            "border": None,
            "bottom": None,
            "display": None,
            "flex": None,
            "flex_flow": None,
            "grid_area": None,
            "grid_auto_columns": None,
            "grid_auto_flow": None,
            "grid_auto_rows": None,
            "grid_column": None,
            "grid_gap": None,
            "grid_row": None,
            "grid_template_areas": None,
            "grid_template_columns": None,
            "grid_template_rows": None,
            "height": None,
            "justify_content": None,
            "justify_items": None,
            "left": None,
            "margin": None,
            "max_height": None,
            "max_width": None,
            "min_height": None,
            "min_width": None,
            "object_fit": None,
            "object_position": None,
            "order": None,
            "overflow": None,
            "overflow_x": None,
            "overflow_y": None,
            "padding": None,
            "right": None,
            "top": None,
            "visibility": None,
            "width": None
          }
        },
        "defa57507bd941789859dc7fc7480892": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "FloatProgressModel",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "FloatProgressModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "ProgressView",
            "bar_style": "success",
            "description": "",
            "description_tooltip": None,
            "layout": "IPY_MODEL_6bdd2c9fb05344aeaf017991219ae69b",
            "max": 267844284,
            "min": 0,
            "orientation": "horizontal",
            "style": "IPY_MODEL_d20627e707184f27b668fcbd35900acb",
            "value": 267844284
          }
        },
        "e066e18f1b564c56b78ad735773c3c64": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "DescriptionStyleModel",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "efd5eee6ecf0435fb302c941cc80e7ff": {
          "model_module": "@jupyter-widgets/base",
          "model_module_version": "1.2.0",
          "model_name": "LayoutModel",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": None,
            "align_items": None,
            "align_self": None,
            "border": None,
            "bottom": None,
            "display": None,
            "flex": None,
            "flex_flow": None,
            "grid_area": None,
            "grid_auto_columns": None,
            "grid_auto_flow": None,
            "grid_auto_rows": None,
            "grid_column": None,
            "grid_gap": None,
            "grid_row": None,
            "grid_template_areas": None,
            "grid_template_columns": None,
            "grid_template_rows": None,
            "height": None,
            "justify_content": None,
            "justify_items": None,
            "left": None,
            "margin": None,
            "max_height": None,
            "max_width": None,
            "min_height": None,
            "min_width": None,
            "object_fit": None,
            "object_position": None,
            "order": None,
            "overflow": None,
            "overflow_x": None,
            "overflow_y": None,
            "padding": None,
            "right": None,
            "top": None,
            "visibility": None,
            "width": None
          }
        },
        "f0e7c66148a04caabdc8bff32f55453e": {
          "model_module": "@jupyter-widgets/controls",
          "model_module_version": "1.5.0",
          "model_name": "DescriptionStyleModel",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "f2d22145a90947e1bfa8d00ab6f2e266": {
          "model_module": "@jupyter-widgets/base",
          "model_module_version": "1.2.0",
          "model_name": "LayoutModel",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": None,
            "align_items": None,
            "align_self": None,
            "border": None,
            "bottom": None,
            "display": None,
            "flex": None,
            "flex_flow": None,
            "grid_area": None,
            "grid_auto_columns": None,
            "grid_auto_flow": None,
            "grid_auto_rows": None,
            "grid_column": None,
            "grid_gap": None,
            "grid_row": None,
            "grid_template_areas": None,
            "grid_template_columns": None,
            "grid_template_rows": None,
            "height": None,
            "justify_content": None,
            "justify_items": None,
            "left": None,
            "margin": None,
            "max_height": None,
            "max_width": None,
            "min_height": None,
            "min_width": None,
            "object_fit": None,
            "object_position": None,
            "order": None,
            "overflow": None,
            "overflow_x": None,
            "overflow_y": None,
            "padding": None,
            "right": None,
            "top": None,
            "visibility": None,
            "width": None
          }
        }
      }
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}
